Repository SaintALY/get_a_friend_seriously, pull requests merged in 2022-02, with the labels that each got.

#19 Setup device two
  db/migrate/20220222103719_add_description_to_user.rb
  db/migrate/20220222104635_add_lastname_to_user.rb
  db/schema.rb
Labels: bug

#29 added controller offers
  app/controllers/offers_controller.rb
  config/routes.rb
Labels: enhancement

#35 Cloud images
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/offers_controller.rb
  app/models/offer.rb
  app/models/user.rb
  app/views/offers/index.html.erb
  app/views/offers/new.html.erb
  config/environments/development.rb
  config/routes.rb
  config/storage.yml
  db/migrate/20220221155331_create_offers.rb
  db/migrate/20220222160529_create_active_storage_tables.active_storage.rb
  db/schema.rb
  db/seeds.rb
Labels: bug, enhancement

#42 made all the links clickable
  app/views/layouts/components/_navbar.html.erb
  app/views/offers/index.html.erb
  app/views/offers/show.html.erb
Labels: bug, enhancement

#47 made booking possible
  app/controllers/bookings_controller.rb
  app/controllers/offers_controller.rb
  app/models/offer.rb
  app/models/user.rb
  app/views/offers/new.html.erb
  app/views/offers/show.html.erb
  config/routes.rb
Labels: bug, enhancement

#48 fixed the double display of notice message
  app/controllers/bookings_controller.rb
  app/controllers/offers_controller.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/layouts/components/_device.html.erb
Labels: bug

#49 added upload option with devise for avatar photos
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/models/application_record.rb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
  db/migrate/20220222103719_add_description_to_user.rb
  db/schema.rb
  db/seeds.rb
Labels: bug, enhancement

#53 added some style to offer view
  app/views/devise/shared/_links.html.erb
  app/views/offers/show.html.erb
Labels: bug, enhancement

#63 added logic to show avatar if exists or placeholder avatar if not
  app/views/layouts/components/_navbar.html.erb
Labels: bug, enhancement

#65 added bookings to dashboard >> needs styling
  app/controllers/bookings_controller.rb
  app/controllers/dashboards_controller.rb
  app/views/dashboards/show.html.erb
  config/routes.rb
Labels: bug, enhancement

#68 Frontend2
  app/assets/stylesheets/components/_user_card.scss
  app/assets/stylesheets/pages/_dashboard.scss
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_login.scss
  app/views/dashboards/show.html.erb
  app/views/offers/index.html.erb
  app/views/offers/new.html.erb
Labels: bug, enhancement

#69 added seed images and show profile pictures on offers now
  app/controllers/offers_controller.rb
  app/views/offers/index.html.erb
  db/seeds.rb
Labels: bug

#71 fixed map and made all card images the same size
  app/views/offers/index.html.erb
Labels: bug

#72 corrected styling and cards
  app/assets/stylesheets/components/_user_card.scss
  app/assets/stylesheets/pages/_dashboard.scss
  app/views/dashboards/show.html.erb
  app/views/offers/index.html.erb
  app/views/offers/new.html.erb
Labels: bug, enhancement

#74 fixed show
  app/controllers/dashboards_controller.rb
Labels: bug
